version: "3.3"

services:
  nanominer:
    runtime: nvidia
    build: nanominer/
    restart: always
    command: ./nanominer /config.ini
    volumes:
      - ./config.ini:/app/config.ini
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all